version: "2"
services:
  logrotate:
    build: .
    container_name: yfix_test_logrotate
    restart: always
    volumes:
      - ./docker/etc/supervisor/conf.d/:/etc/supervisor/conf.d/
      - ./docker/var/log/supervisor:/var/log/supervisor
      - ./docker/etc/cron.d/:/etc/cron.d/
      - ./docker/etc/cron.hourly/:/etc/cron.hourly/
      - ./docker/etc/cron.daily/:/etc/cron.daily/
      - ./docker/etc/cron.weekly/:/etc/cron.weekly/
      - ./docker/etc/cron.monthly/:/etc/cron.monthly/
      - ./docker/etc/logrotate.conf:/etc/logrotate.conf
      - ./docker/etc/logrotate.d/:/etc/logrotate.d/
      - ./docker/var/log/logrotate:/var/log/logrotate
